-- Admin-managed warehouse catalog. Seed the existing three sites, then allow
-- Underboss+ to add more as new properties come online.

create table public.inventory_warehouses (
  id smallint generated by default as identity primary key,
  name text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint inventory_warehouses_name_len
    check (char_length(name) between 1 and 80),
  constraint inventory_warehouses_name_unique unique (name)
);

create index inventory_warehouses_active_sort_idx
  on public.inventory_warehouses (is_active, sort_order, name);

insert into public.inventory_warehouses (id, name, sort_order)
values
  (1, 'Warehouse 1', 1),
  (2, 'Warehouse 2', 2),
  (3, 'Warehouse 3', 3);

select setval(
  pg_get_serial_sequence('public.inventory_warehouses', 'id'),
  (select coalesce(max(id), 1) from public.inventory_warehouses)
);

alter table public.inventory_warehouses enable row level security;

revoke all on public.inventory_warehouses from authenticated;
grant select on public.inventory_warehouses to authenticated;
grant insert, update, delete on public.inventory_warehouses to authenticated;

-- Anyone who can open Inventory may read the catalog (for tabs / labels).
create policy "inventory readers see warehouses"
  on public.inventory_warehouses
  for select
  to authenticated
  using (public.vanta_can_access_inventory() or public.vanta_is_admin());

create policy "admins manage warehouses"
  on public.inventory_warehouses
  for all
  to authenticated
  using (public.vanta_is_admin())
  with check (public.vanta_is_admin());

-- Point movement + access rows at the catalog instead of a hard 1/2/3 check.
alter table public.inventory_movements
  drop constraint if exists inventory_movements_warehouse_check;

alter table public.inventory_warehouse_access
  drop constraint if exists inventory_warehouse_access_warehouse_check;

alter table public.inventory_movements
  add constraint inventory_movements_warehouse_fkey
    foreign key (warehouse) references public.inventory_warehouses (id)
    on delete restrict;

alter table public.inventory_warehouse_access
  add constraint inventory_warehouse_access_warehouse_fkey
    foreign key (warehouse) references public.inventory_warehouses (id)
    on delete cascade;

create or replace function public.vanta_default_inventory_warehouse()
returns smallint
language sql
stable
security definer
set search_path = public
as $$
  select w.id
  from public.inventory_warehouses w
  where w.is_active
  order by w.sort_order, w.id
  limit 1;
$$;

grant execute on function public.vanta_default_inventory_warehouse() to authenticated;

-- Outbound guard uses the warehouse display name.
create or replace function public.vanta_guard_inventory_outbound()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  on_hand bigint;
  warehouse_label text;
begin
  if new.direction <> 'outbound' then
    return new;
  end if;

  select coalesce(sum(
    case when m.direction = 'inbound' then m.quantity else -m.quantity end
  ), 0)
    into on_hand
  from public.inventory_movements m
  where m.item_id = new.item_id
    and m.warehouse = new.warehouse;

  if on_hand < new.quantity then
    select w.name into warehouse_label
    from public.inventory_warehouses w
    where w.id = new.warehouse;

    raise exception
      'Not enough stock in % (have %, need %)',
      coalesce(warehouse_label, 'warehouse'), on_hand, new.quantity
      using errcode = 'P0001';
  end if;

  return new;
end;
$$;

-- Remit approvals land in the first active warehouse (seeded as Warehouse 1).
create or replace function public.vanta_sync_remit_to_inventory()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_item uuid;
  note_text text;
  actor uuid;
  target_warehouse smallint;
begin
  perform set_config('vanta.syncing_remit_inventory', '1', true);

  if tg_op = 'DELETE' then
    delete from public.inventory_movements where remit_log_id = old.id;
    return null;
  end if;

  if old.status = 'approved' and new.status is distinct from 'approved' then
    delete from public.inventory_movements where remit_log_id = new.id;
  end if;

  if new.status <> 'approved' then
    return null;
  end if;

  select t.inventory_item_id
    into target_item
  from public.remit_types t
  where t.id = new.remit_type_id;

  if target_item is null then
    delete from public.inventory_movements where remit_log_id = new.id;
    return null;
  end if;

  target_warehouse := public.vanta_default_inventory_warehouse();
  if target_warehouse is null then
    raise exception 'No active warehouse to receive remit stock'
      using errcode = 'P0001';
  end if;

  note_text := left(
    coalesce(
      nullif(trim(new.description), ''),
      'From approved remit'
    ),
    500
  );
  actor := coalesce(auth.uid(), new.reviewed_by, new.submitted_by);

  insert into public.inventory_movements (
    item_id,
    direction,
    quantity,
    note,
    member_id,
    created_by,
    remit_log_id,
    warehouse
  )
  values (
    target_item,
    'inbound',
    new.quantity,
    note_text,
    new.member_id,
    actor,
    new.id,
    target_warehouse
  )
  on conflict (remit_log_id)
  do update set
    item_id = excluded.item_id,
    quantity = excluded.quantity,
    note = excluded.note,
    member_id = excluded.member_id,
    warehouse = excluded.warehouse;

  return null;
end;
$$;

drop view if exists public.inventory_stock;
drop view if exists public.inventory_warehouse_stock;

-- Crew-wide totals (admins only). Per-warehouse breakdown is in the warehouse view.
create view public.inventory_stock as
select
  i.id as item_id,
  i.name as item_name,
  i.is_active,
  i.created_at,
  coalesce(b.inbound_total, 0)::bigint as inbound_total,
  coalesce(b.outbound_total, 0)::bigint as outbound_total,
  coalesce(b.on_hand, 0)::bigint as on_hand
from public.inventory_items i
left join public.vanta_inventory_balances() b on b.item_id = i.id
where public.vanta_is_admin();

grant select on public.inventory_stock to authenticated;

create view public.inventory_warehouse_stock as
select
  w.id as warehouse,
  w.name as warehouse_name,
  w.sort_order,
  w.is_active as warehouse_active,
  i.id as item_id,
  i.name as item_name,
  i.is_active,
  i.created_at,
  coalesce(b.inbound_total, 0)::bigint as inbound_total,
  coalesce(b.outbound_total, 0)::bigint as outbound_total,
  coalesce(b.on_hand, 0)::bigint as on_hand
from public.inventory_items i
cross join public.inventory_warehouses w
left join public.vanta_inventory_warehouse_balances() b
  on b.item_id = i.id and b.warehouse = w.id
where public.vanta_is_admin()
   or public.vanta_has_warehouse_access(w.id);

grant select on public.inventory_warehouse_stock to authenticated;
